include:
  - project: 'QubesOS/qubes-continuous-integration'
    ref: main
    file: '/r4.2/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    ref: main
    file: '/r4.2/gitlab-vm-debian-build-template.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    ref: main
    file: '/r4.3/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    ref: main
    file: '/r4.3/gitlab-vm-debian-build-template.yml'

default:
  tags:
    - vm

after_script:
  - ls -l ~/qubes-builder/qubes-src/linux-template-builder/rpm/noarch

variables:
  COMPONENTS: linux-template-builder
  USE_DIST_BUILD_TOOL: 0

r4.2:prep:sources:
  extends: .r4.2_components_prepare
  variables:
    qb_opts: "-c template-whonix"

r4.3:prep:sources:
  extends: .r4.3_components_prepare
  variables:
    qb_opts: "-c template-whonix"
