#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

if [ "$VERBOSE" -ge 2 -o "$DEBUG" == "1" ]; then
    set -x
fi

source "${SCRIPTSDIR}/vars.sh"
source "${SCRIPTSDIR}/distribution.sh"

##### '=========================================================================
debug ' Cleaning up...'
##### '=========================================================================

# ==============================================================================
# Execute any template flavor or sub flavor 'pre' scripts
# ==============================================================================
buildStep "${0}" "pre"

#### '-------------------------------------------------------------------------
info ' Cleaning up  any left over files from installation'
#### '-------------------------------------------------------------------------
rm -rf "${INSTALLDIR}/var/cache/apt/archives"
rm -rf "${INSTALLDIR}/var/cache/apt/pkgcache.bin"
rm -rf "${INSTALLDIR}/var/cache/apt/srcpkgcache.bin"
rm -f "${INSTALLDIR}/etc/apt/sources.list.d/qubes-builder.list"
rm -rf "${INSTALLDIR}/${TMPDIR}"
rm -f "${INSTALLDIR}/var/lib/systemd/random-seed"
rm -f "${INSTALLDIR}/var/lib/exim4/config.autogenerated"
rm -f "${INSTALLDIR}/etc/mailname"
sed -i /dc_other_hostnames=.*/d  "${INSTALLDIR}/etc/exim4/update-exim4.conf.conf"
sed -i '/./{H;$!d};x;/dc_other_hostnames/d'  "${INSTALLDIR}/var/cache/debconf/config.dat"
sed -i '/./{H;$!d};x;/exim4\/mailname/d'  "${INSTALLDIR}/var/cache/debconf/config.dat"
sed -i '/./{H;$!d};x;/dc_other_hostnames/d'  "${INSTALLDIR}/var/cache/debconf/config.dat-old"
sed -i '/./{H;$!d};x;/exim4\/mailname/d'  "${INSTALLDIR}/var/cache/debconf/config.dat-old"

# ==============================================================================
# Execute any template flavor or sub flavor 'post' scripts
# ==============================================================================
buildStep "${0}" "post"
